# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"3\n\rSignUpRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\",\n\x0eSignUpResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\"3\n\rSignInRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\",\n\x0eSignInResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t2w\n\x0bUserService\x12\x33\n\x06SignUp\x12\x13.user.SignUpRequest\x1a\x14.user.SignUpResponse\x12\x33\n\x06SignIn\x12\x13.user.SignInRequest\x1a\x14.user.SignInResponseb\x06proto3')



_SIGNUPREQUEST = DESCRIPTOR.message_types_by_name['SignUpRequest']
_SIGNUPRESPONSE = DESCRIPTOR.message_types_by_name['SignUpResponse']
_SIGNINREQUEST = DESCRIPTOR.message_types_by_name['SignInRequest']
_SIGNINRESPONSE = DESCRIPTOR.message_types_by_name['SignInResponse']
SignUpRequest = _reflection.GeneratedProtocolMessageType('SignUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUpRequest)
  })
_sym_db.RegisterMessage(SignUpRequest)

SignUpResponse = _reflection.GeneratedProtocolMessageType('SignUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUPRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUpResponse)
  })
_sym_db.RegisterMessage(SignUpResponse)

SignInRequest = _reflection.GeneratedProtocolMessageType('SignInRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignInRequest)
  })
_sym_db.RegisterMessage(SignInRequest)

SignInResponse = _reflection.GeneratedProtocolMessageType('SignInResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNINRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.SignInResponse)
  })
_sym_db.RegisterMessage(SignInResponse)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNUPREQUEST._serialized_start=20
  _SIGNUPREQUEST._serialized_end=71
  _SIGNUPRESPONSE._serialized_start=73
  _SIGNUPRESPONSE._serialized_end=117
  _SIGNINREQUEST._serialized_start=119
  _SIGNINREQUEST._serialized_end=170
  _SIGNINRESPONSE._serialized_start=172
  _SIGNINRESPONSE._serialized_end=216
  _USERSERVICE._serialized_start=218
  _USERSERVICE._serialized_end=337
# @@protoc_insertion_point(module_scope)
